Update gt7-extramenus.py
mistakenchicken/gt7-extramenus pull request #3
Opened 2022-06-29 03:15 UTC by dehydratedH2O

improved runtime by roughly 20sec per cycle by skipping extra waits and inputs for engine ticket acceptance. tested overnight on PS5 using GT7 physical disc.

2022-07-01 19:40 UTC, mistakenchicken requested changes
Hi, thank you so much for your contribution! I will merge as soon as you address the comment on the pull request. The rest looks good!

2022-07-01 19:40 UTC, mistakenchicken commented on gt7-extramenus.py
> +    sleep(2.5)
Please discard this change, in my testing, sometimes it could take a bit longer to load the menu.

2022-07-02 05:01 UTC, dehydratedH2O commented
reverted to original timing as requested for that one line

2022-07-05 06:19 UTC, merged

2022-07-05 06:22 UTC, mistakenchicken commented
Thank you @dehydratedH2O and sorry for taking so long to merge, I was quite busy this weekend.